apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ib03c4xel-go 
  janus-idp.io/tekton: ib03c4xel-go
  backstage.io/kubernetes-id: ib03c4xel-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ib03c4xel-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  