apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ib03c4xel-go-gitops
  description: This is GitOps manifest for ib03c4xel-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ib03c4xel-go
    janus-idp.io/tekton: ib03c4xel-go
    backstage.io/kubernetes-id: ib03c4xel-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ib03c4xel-go
